# I dont like reaching through b
unbind C-b

set -g prefix C-x

# My keybinds
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind C-x send-prefix

# Love emacs, what can I do?
set -g mode-keys emacs
set -g status-keys emacs
set -s escape-time 0
