#!/usr/bin/env bash

RICETHEME=ren01
PATH="$HOME/.config/bspwm/scripts:$PATH"

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1


function get_values() {
    DEFNETWORK=$(ip route | grep '^default' | awk '{print $5}' | head -n1)
    CARD=$(ls -1 /sys/class/backlight/)
    power_supply_files=$(ls /sys/class/power_supply/)

    for file in $power_supply_files
    do
	    if [ -e "/sys/class/power_supply/$file/capacity" ]; then
		    battery_file=$file
        fi

        if [ -e "/sys/class/power_supply/$file/online" ]; then
            adapter_file=$file
        fi
    done

    BATTERY="$battery_file"
    ADAPTER="$adapter_file"
}

set_values() {
	if [[ "$DEFNETWORK" ]]; then
		sed -i -e "s/sys_network_interface = .*/sys_network_interface = $DEFNETWORK/g" $HOME/.config/bspwm/scripts/system.ini
	fi
	if [[ "$ADAPTER" ]]; then
		sed -i -e "s/sys_adapter = .*/sys_adapter = $ADAPTER/g" $HOME/.config/bspwm/scripts/system.ini
	fi
	if [[ "$BATTERY" ]]; then
		sed -i -e "s/sys_battery = .*/sys_battery = $BATTERY/g" $HOME/.config/bspwm/scripts/system.ini
	fi
	if [[ "$CARD" ]]; then
		sed -i -e "s/sys_graphics_card = .*/sys_graphics_card = $CARD/g" $HOME/.config/bspwm/scripts/system.ini
	fi
}

# if [[ ! -f "$SFILE" ]]; then
# 	get_values
# 	set_values
# 	touch $HOME/.config/bspwm/scripts/.sys
# fi

workspaces() {
    namE=1
    monitores=$(bspc query -M | head -1)
    bspc monitor "${monitores}" -n $"namE" -d '1' '2' '3' '4' '5' '6'
}

monitors() {
    space=0

    # i create a query to store all the ports that are active 
    monitor_query=()

    # whith the for I can obtain the name of that monitor just to 
    # store in the query
    for monitor in $(xrandr | grep " connected " | awk '{ print$1 }'); do
        monitor_query[${space}]+=${monitor};
        (( space++ ))
    done
    
    # now that we have the names stored, we proceed to change the monitors
    if xrandr | grep "${monitor_query[1]} disconnected"; then
        xrandr --output "${monitor_query[1]}" --off --output "${monitor_query[0]}" --auto
        # bspc monitor "${montiro_query[0]}" -d '1' '2' '3' '4' '5' '6' 
        workspaces
    else
        xrandr --output "${monitor_query[0]}" --off --output "${monitor_query[1]}" --mode 1920x1080 --rate 165.00
        # bspc monitor "${montiro_query[1]}" -d '1' '2' '3' '4' '5' '6' 
        workspaces
    fi

    # in my case I only use one monitor for default, i really dont mind using two monitors
    # also de refresh rate from my monitor is higher, so you can change that variables depend
    # of you setup
}

# This is just a function that restarts the panel.
# Nothing fancy here.
reset_panel() {
    pkill -x panel
    setsid panel &
}

# Monitors
monitors

bspc config external_rules_command        $HOME/.config/bspwm/scripts/ExternalRules
bspc config split_ratio                   0.52
bspc config single_monocle                true
bspc config borderless_monocle            false
bspc config gapless_monocle               false

bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         false
bspc config pointer_motion_interval       5
bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

bspc wm --adopt-orphans


# Terminate already running polybar, eww, picom, sxhkd and dunst instances
processes=("picom" "polybar" "eww" "sxhkd" "dunst")

for process in "${processes[@]}"; do
  if pidof -q "$process"; then
    pkill -x "$process" > /dev/null; sleep 0.1
  fi
done

# Reload terminal colors
cat $HOME/.config/bspwm/configuration/$RICETHEME/alacrittyrc > $HOME/.config/alacritty/alacritty.yml 

# Launch picom // If you have old hardware or encounter problems uncomment the picom "--legacy-backends" line and comment the current one.
picom --config $HOME/.config/bspwm/configuration/$RICETHEME/picom.conf &
#picom --legacy-backends --config $HOME/.config/bspwm/rices/$RICETHEME/picom.conf &

# Launch bars and/or eww widgets
$HOME/.config/bspwm/configuration/$RICETHEME/Theme.sh

# Set random wallpaper for this rice
# feh -z --no-fehbg --bg-fill $HOME/.config/bspwm/rices/$RICETHEME/walls/
# If you don't want the random wallpaper feature, comment the line above "feh -z..." 
# and add the one you use.
nitrogen --restore &

# Start the betterlockscreen with config files
betterlockscreen -u /.config/betterlockscreen

# Launch dunst notification daemon
dunst -config $HOME/.config/bspwm/configuration/$RICETHEME/dunstrc &

# Reload sxhkd daemon
sxhkd -c $HOME/.config/bspwm/sxhkdrc &

# Launch polkit
pgrep -x polkit-gnome-au > /dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Fix cursor
xsetroot -cursor_name left_ptr
