require "options/keymaps"
require "plugins"
require "options/options"
require "options/colorizer"
require "options/lualine"
require "options/conform"
require "options/bufferline"
require "options/indented-line"
